import Link from "next/link";
import {PublicFooter} from "@/components/portfolio/public-footer";
import {createClient} from "@/lib/supabase/server";
import {PublicNav} from "@/components/portfolio/public-nav";
import {getPageMetadata} from "@/lib/site/seo";


export async function generateMetadata(){return getPageMetadata("services",{"title":"Services — Okoh Wisdom","description":"Software, product, design and AI support focused on turning real problems into useful digital solutions.","path":"/services"});}
export default async function ServicesPage(){
 const s=await createClient();
 const {data:items}=await s.from("services").select("id,title,slug,short_description,full_description,icon,featured_image_url,starting_price,currency,cta_label,cta_url,featured,service_pricing_links(pricing_package_id,pricing_packages(package_name,starting_price,currency,custom_quote,visibility))").eq("enabled",true).is("deleted_at",null).order("sort_order");
 return <main className="min-h-screen bg-[#050812] text-white"><PublicNav/><section className="mx-auto w-[min(1320px,calc(100%-32px))] py-16 sm:w-[min(1320px,calc(100%-40px))] sm:py-20"><p className="text-xs font-semibold tracking-[.18em] text-[#6f8cff]">SERVICES</p><h1 className="mt-5 max-w-4xl text-[clamp(2.8rem,7vw,5.8rem)] font-semibold leading-[.95] tracking-[-.05em]">Bring the problem. We’ll work toward the right digital solution.</h1><p className="mt-6 max-w-2xl text-base leading-8 text-white/45 sm:text-lg">I work across software, product thinking, design and AI. The service is the method; the useful outcome is the point.</p>{items?.length?<div className="mt-12 grid gap-4 md:grid-cols-2 sm:mt-14">{items.map((x,i)=><article key={x.id} className={`service-card group relative overflow-hidden rounded-[28px] border border-white/[.08] bg-[linear-gradient(145deg,rgba(10,24,57,.78),rgba(7,9,16,.94))] p-6 sm:p-8 ${i===0&&x.featured?"md:col-span-2":""}`}>{x.featured_image_url?<div className="mb-6 aspect-[16/7] overflow-hidden rounded-2xl border border-white/[.08] bg-[#081024]"><div className="h-full w-full bg-cover bg-center transition duration-700 group-hover:scale-[1.03]" style={{backgroundImage:`url("${x.featured_image_url}")`}}/></div>:x.icon&&<p className="text-xl text-[#8097ff]">{x.icon}</p>}<h2 className="mt-8 text-3xl font-semibold tracking-[-.04em]">{x.title}</h2><p className="mt-4 max-w-2xl text-base leading-7 text-white/50">{x.full_description||x.short_description}</p>{x.starting_price!=null&&<p className="mt-6 text-sm text-white/35">From {x.currency==="NGN"?"₦":x.currency+" "}{Number(x.starting_price).toLocaleString()}</p>}<Link href={x.cta_url||"/contact"} className="mt-7 inline-flex min-h-11 items-center rounded-full border border-[#4168d6]/25 bg-[#0b1734]/50 px-4 text-sm text-white/75 transition hover:border-[#6385ff]/45 hover:bg-[#112451]">{x.cta_label||"Let's talk ↗"}</Link></article>)}</div>:<div className="mt-14 rounded-3xl border border-dashed border-white/10 p-10 text-center text-sm text-white/35 sm:p-14">Services will appear here once enabled in the CMS.</div>}</section><PublicFooter/></main>
}
