import Link from "next/link";
import {Fragment, type ReactNode} from "react";
import {createClient} from "@/lib/supabase/server";
import {HeroRotator} from "@/components/portfolio/hero-rotator";
import {PublicNav} from "@/components/portfolio/public-nav";

export default async function HomePage(){
 const s=await createClient();
 const [
  {data:h},{data:sections},{data:featured},{data:about},{data:designs},
  {data:skills},{data:experiments},{data:services},{data:pricingSettings},
  {data:packages},{data:nowItems}
 ]=await Promise.all([
  s.from("hero_settings").select("*").eq("singleton_key","default").single(),
  s.from("page_sections").select("*").eq("page_key","home").eq("enabled",true).order("sort_order"),
  s.from("project_publications").select("project_id,slug,title,short_description,status,confidential,snapshot").eq("featured",true).order("sort_order").limit(6),
  s.from("about_profile").select("headline,introduction,portrait_url").eq("singleton_key","default").single(),
  s.from("designs").select("id,title,client,year,image_url,design_categories(name)").eq("visibility","public").eq("featured",true).is("deleted_at",null).order("sort_order").limit(6),
  s.from("skills").select("id,name,group_name,sort_order").eq("is_visible",true).order("group_name").order("sort_order"),
  s.from("experiments").select("id,title,slug,description,status,technology,image_url").eq("visibility","public").eq("featured",true).is("deleted_at",null).order("sort_order").limit(3),
  s.from("services").select("id,title,short_description,icon,cta_label,cta_url,featured").eq("enabled",true).is("deleted_at",null).order("featured",{ascending:false}).order("sort_order").limit(4),
  s.from("pricing_settings").select("*").eq("singleton_key","default").single(),
  s.from("pricing_packages").select("*").eq("visibility",true).is("deleted_at",null).order("sort_order").limit(3),
  s.from("now_items").select("*").eq("visible",true).order("sort_order")
 ]);
 const rawWords=h?.rotating_words;
 const words=Array.isArray(rawWords)?rawWords.filter((x:unknown):x is string=>typeof x==="string"):["WORK.","MATTER.","MOVE.","SCALE.","CONNECT."];
 const groups=["Build","Design","Think","AI"];

 const block:Record<string,ReactNode>={
  hero:<section className="mx-auto grid min-h-[calc(100vh-92px)] w-[min(1440px,calc(100%-40px))] items-center gap-10 py-12 lg:grid-cols-[minmax(0,1fr)_360px] lg:py-16">
   <div><p className="mb-7 text-[11px] font-semibold tracking-[.22em] text-white/35">{h?.eyebrow??"WISDOM / WIKIS TECH · LAGOS, NG"}</p><HeroRotator line1={h?.headline_line_1??"I BUILD DIGITAL"} line2={h?.headline_line_2??"THINGS THAT"} words={words} enabled={h?.rotation_enabled??true} intervalMs={h?.rotation_interval_ms??2200}/><p className="mt-8 max-w-2xl text-base leading-7 text-white/50 sm:text-lg">{h?.supporting_text}</p><div className="mt-7 flex flex-wrap gap-3"><Link href={h?.primary_cta_url??"#work"} className="rounded-full bg-white px-5 py-3 text-sm font-semibold text-black">{h?.primary_cta_label??"View Selected Work ↓"}</Link><Link href={h?.secondary_cta_url??"/contact"} className="rounded-full border border-white/10 px-5 py-3 text-sm font-medium text-white/70">{h?.secondary_cta_label??"Let's Work Together ↗"}</Link></div></div>
   <aside className="relative hidden min-h-[500px] lg:block"><div className="hero-portrait absolute inset-3 overflow-hidden rounded-[38px] border border-white/10 bg-white/[.025]">{h?.hero_media_url?<div className="h-full w-full bg-cover bg-center" style={{backgroundImage:`url("${h.hero_media_url}")`}} role="img" aria-label="Wisdom"/>:<><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_35%,rgba(40,103,232,.18),transparent_35%),linear-gradient(180deg,rgba(255,255,255,.04),rgba(255,255,255,.01))]"/><div className="absolute inset-x-8 bottom-8 rounded-2xl border border-white/[.08] bg-black/20 p-4 backdrop-blur"><p className="text-xs font-semibold tracking-[.18em] text-white/35">PORTRAIT / HERO MEDIA</p><p className="mt-2 text-sm text-white/55">Your image will live here. Add it from Home Editor.</p></div></>}</div></aside>
  </section>,

  selected_work:<section id="work" className="mx-auto w-[min(1320px,calc(100%-40px))] py-24"><p className="text-xs font-semibold tracking-[.18em] text-[#6f8cff]">SELECTED WORK</p><div className="mt-4 flex items-end justify-between gap-4"><h2 className="text-4xl font-semibold tracking-[-.04em] sm:text-6xl">Work that explains how I think.</h2><Link href="/work" className="hidden text-sm text-white/50 sm:block">View all work ↗</Link></div>{featured?.length?<div className="mt-10 grid gap-4 md:grid-cols-2">{featured.map((p,i)=><Link key={p.project_id} href={`/work/${p.slug}`} className={`group rounded-3xl border border-white/[.08] bg-white/[.025] p-6 transition hover:-translate-y-1 hover:bg-white/[.045] ${i===0?"md:col-span-2 md:min-h-72":""}`}><p className="text-xs text-white/30">0{i+1} · {p.status.replaceAll("_"," ")}</p><h3 className="mt-16 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">{p.title}</h3><p className="mt-3 max-w-xl text-sm leading-6 text-white/45">{p.short_description}</p></Link>)}</div>:<Empty text="Featured projects will appear here after publishing them from the CMS."/>}</section>,

  about_preview:<section className="mx-auto grid w-[min(1200px,calc(100%-40px))] gap-8 border-t border-white/[.08] py-24 lg:grid-cols-[1fr_300px]"><div><p className="text-xs font-semibold tracking-[.18em] text-[#6f8cff]">ABOUT</p><h2 className="mt-5 max-w-3xl text-4xl font-semibold tracking-[-.04em] sm:text-6xl">{about?.headline}</h2><p className="mt-6 max-w-2xl text-base leading-8 text-white/50">{about?.introduction}</p><Link href="/about" className="mt-7 inline-block text-sm text-white/70">More about me ↗</Link></div><div className="relative hidden min-h-80 lg:block">{about?.portrait_url?<div className="absolute inset-0 rounded-[30px] border border-white/10 bg-cover bg-center" style={{backgroundImage:`url("${about.portrait_url}")`}}/>:<div className="absolute inset-0 rounded-[30px] border border-white/10 bg-white/[.025]"/>}</div></section>,

  capabilities:<section className="mx-auto w-[min(1200px,calc(100%-40px))] py-24"><p className="text-xs font-semibold tracking-[.18em] text-[#6f8cff]">CAPABILITIES</p><h2 className="mt-4 max-w-3xl text-4xl font-semibold tracking-[-.04em] sm:text-6xl">Different disciplines. One problem-solving process.</h2><div className="mt-10 grid gap-px overflow-hidden rounded-3xl border border-white/[.08] bg-white/[.08] md:grid-cols-2">{groups.map(g=>{const items=(skills??[]).filter(x=>x.group_name===g);return <article key={g} className="bg-[#08090e] p-6 sm:p-8"><p className="text-xs font-semibold tracking-[.16em] text-[#8097ff]">{g.toUpperCase()}</p><p className="mt-8 text-base leading-8 text-white/45">{items.length?items.map(x=>x.name).join(" · "):"Add skills from the CMS."}</p></article>})}</div></section>,

  creative_archive:<section className="mx-auto w-[min(1320px,calc(100%-40px))] py-24"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-semibold tracking-[.18em] text-[#6f8cff]">VISUAL ARCHIVE</p><h2 className="mt-4 max-w-4xl text-4xl font-semibold tracking-[-.04em] sm:text-6xl">Design work outside the case-study format.</h2></div><Link href="/archive" className="hidden text-sm text-white/50 sm:block">View Archive ↗</Link></div>{designs?.length?<div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{designs.map(d=><Link href="/archive" key={d.id} className="group overflow-hidden rounded-2xl border border-white/[.08] bg-white/[.025]"><div className="aspect-[4/5] bg-cover bg-center transition duration-500 group-hover:scale-[1.02]" style={{backgroundImage:`url("${d.image_url}")`}}/><div className="p-4"><p className="text-[10px] uppercase tracking-[.16em] text-white/30">{(d.design_categories as {name?:string}|null)?.name||"Design"}{d.year?` · ${d.year}`:""}</p><h3 className="mt-2 text-lg font-semibold">{d.title}</h3><p className="mt-1 text-sm text-white/35">{d.client}</p></div></Link>)}</div>:<Empty text="Featured design work will appear here from the Design Archive CMS."/>}</section>,

  lab_preview:<section className="mx-auto w-[min(1320px,calc(100%-40px))] py-24"><div className="grid gap-8 lg:grid-cols-[.65fr_1.35fr]"><div><p className="text-xs font-semibold tracking-[.18em] text-[#6f8cff]">THE LAB</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] sm:text-6xl">Curiosity gets its own workspace.</h2><p className="mt-5 max-w-md text-base leading-7 text-white/45">Games, prototypes, AI experiments and interface studies that don’t need a client brief to exist.</p><Link href="/lab" className="mt-7 inline-block text-sm text-white/70">Enter the Lab ↗</Link></div><div className="space-y-3">{experiments?.length?experiments.map((x,i)=><Link key={x.id} href={`/lab/${x.slug}`} className="grid gap-4 rounded-2xl border border-white/[.08] bg-white/[.025] p-5 transition hover:bg-white/[.045] sm:grid-cols-[80px_1fr_auto] sm:items-center"><span className="text-2xl text-white/15">0{i+1}</span><div><h3 className="text-lg font-semibold">{x.title}</h3><p className="mt-1 text-sm text-white/35">{x.description}</p></div><span className="text-sm text-white/40">↗</span></Link>):<Empty text="Featured Lab experiments will appear here."/>}</div></div></section>,

  services:<section className="mx-auto w-[min(1200px,calc(100%-40px))] py-24"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-semibold tracking-[.18em] text-[#6f8cff]">SERVICES</p><h2 className="mt-4 max-w-4xl text-4xl font-semibold tracking-[-.04em] sm:text-6xl">What can we build?</h2></div><Link href="/services" className="hidden text-sm text-white/50 sm:block">All services ↗</Link></div>{services?.length?<div className="mt-10 divide-y divide-white/[.08] border-y border-white/[.08]">{services.map((x,i)=><Link href={x.cta_url||"/contact"} key={x.id} className="grid gap-3 py-6 transition hover:pl-2 md:grid-cols-[80px_1fr_1fr_auto] md:items-center"><span className="text-sm text-white/20">0{i+1}</span><h3 className="text-xl font-semibold">{x.title}</h3><p className="text-sm leading-6 text-white/40">{x.short_description}</p><span className="text-sm text-white/35">↗</span></Link>)}</div>:<Empty text="Enabled services will appear here."/>}</section>,

  pricing:<section className="mx-auto w-[min(1200px,calc(100%-40px))] py-24">{pricingSettings?.enabled?<><p className="text-xs font-semibold tracking-[.18em] text-[#6f8cff]">PRICING</p><div className="mt-4 flex items-end justify-between gap-4"><h2 className="max-w-3xl text-4xl font-semibold tracking-[-.04em] sm:text-6xl">{pricingSettings.heading}</h2><Link href="/pricing" className="hidden text-sm text-white/50 sm:block">See pricing ↗</Link></div><p className="mt-5 max-w-2xl text-base leading-7 text-white/45">{pricingSettings.description}</p>{packages?.length?<div className="mt-10 grid gap-3 md:grid-cols-3">{packages.map(p=><article key={p.id} className={`rounded-2xl border p-5 ${p.featured?"border-[#5b72ff]/40 bg-[#174fc4]/[.08]":"border-white/[.08] bg-white/[.025]"}`}><p className="text-xs uppercase tracking-[.14em] text-white/30">{p.package_name}</p><p className="mt-8 text-2xl font-semibold">{p.custom_quote?"Custom Quote":p.starting_price!=null?`${p.currency==="NGN"?"₦":p.currency+" "}${Number(p.starting_price).toLocaleString()}`:"Let’s discuss"}</p></article>)}</div>:null}</>:<div className="rounded-3xl border border-white/[.08] bg-white/[.02] p-8"><p className="text-sm text-white/45">Pricing is handled by scope. Tell me what you’re building and we’ll work out a sensible approach.</p><Link href="/contact" className="mt-5 inline-block text-sm text-white/70">Start a conversation ↗</Link></div>}</section>,

  now:<section className="mx-auto w-[min(1200px,calc(100%-40px))] py-24"><p className="text-xs font-semibold tracking-[.18em] text-[#6f8cff]">RIGHT NOW</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] sm:text-6xl">What has my attention.</h2>{nowItems?.length?<div className="mt-10 grid gap-3 md:grid-cols-2">{nowItems.map(x=><article key={x.id} className="rounded-2xl border border-white/[.08] bg-white/[.025] p-5"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-white/30">{x.label}</p>{x.url?<Link href={x.url} className="mt-4 block text-lg text-white/70">{x.text} ↗</Link>:<p className="mt-4 text-lg text-white/70">{x.text}</p>}</article>)}</div>:<Empty text="Add Now items from the CMS to show what you are building, learning and exploring."/>}</section>,

  contact_cta:<section className="mx-auto w-[min(1320px,calc(100%-40px))] py-28"><div className="rounded-[36px] border border-white/[.08] bg-[radial-gradient(circle_at_80%_20%,rgba(40,103,232,.14),transparent_35%),rgba(255,255,255,.025)] p-7 sm:p-12"><p className="text-xs font-semibold tracking-[.18em] text-[#6f8cff]">HAVE AN IDEA?</p><h2 className="mt-5 max-w-4xl text-5xl font-semibold tracking-[-.05em] sm:text-7xl">Let’s build something useful.</h2><p className="mt-6 max-w-2xl text-base leading-7 text-white/45">Whether it’s a product, website, campaign, experiment or something that doesn’t quite fit a category yet—tell me about it.</p><Link href="/contact" className="mt-8 inline-block rounded-full bg-white px-5 py-3 text-sm font-semibold text-black">Start a conversation ↗</Link></div></section>
 };

 return <main className="min-h-screen overflow-hidden bg-[#06070b] text-white"><PublicNav/>{sections?.map(sec=><Fragment key={sec.id}>{block[sec.section_key]??null}</Fragment>)}<footer className="mx-auto flex w-[min(1440px,calc(100%-40px))] flex-wrap items-center justify-between gap-4 border-t border-white/[.07] py-6 text-xs text-white/35"><span>{h?.availability_enabled?"● ":""}{h?.availability_message}</span><span>CODE × DESIGN × AI × STRATEGY</span></footer></main>
}

function Empty({text}:{text:string}){return <div className="mt-10 rounded-3xl border border-dashed border-white/10 p-10 text-center text-sm text-white/35">{text}</div>}
