import Link from "next/link";
import {Fragment, type ReactNode} from "react";
import {createClient} from "@/lib/supabase/server";
import {HeroRotator} from "@/components/portfolio/hero-rotator";
import {PublicNav} from "@/components/portfolio/public-nav";
import {PublicFooter} from "@/components/portfolio/public-footer";
import {getPageMetadata} from "@/lib/site/seo";

export async function generateMetadata(){return getPageMetadata("home",{title:"Okoh Wisdom — Websites, Digital Products & Intelligent Tools",description:"I build useful websites, digital products and intelligent tools by combining software, design, AI and strategy.",path:"/"});}

type PublicationSnapshot={problem?:string;outcome?:string;card_media_url?:string|null;live_url?:string|null};

export default async function HomePage(){
 const s=await createClient();
 const [
  {data:h},{data:sections},{data:featured},{data:about},{data:designs},
  {data:skills},{data:experiments},{data:services},{data:pricingSettings},
  {data:packages},{data:nowItems},{data:testimonials}
 ]=await Promise.all([
  s.from("hero_settings").select("*").eq("singleton_key","default").single(),
  s.from("page_sections").select("*").eq("page_key","home").eq("enabled",true).order("sort_order"),
  s.from("project_publications").select("project_id,slug,title,short_description,status,confidential,snapshot").eq("featured",true).order("sort_order").limit(6),
  s.from("about_profile").select("headline,introduction,portrait_url").eq("singleton_key","default").single(),
  s.from("designs").select("id,title,client,year,image_url,design_categories(name)").eq("visibility","public").eq("featured",true).is("deleted_at",null).order("sort_order").limit(6),
  s.from("skills").select("id,name,group_name,sort_order").eq("is_visible",true).order("group_name").order("sort_order"),
  s.from("experiments").select("id,title,slug,description,status,technology,image_url").eq("visibility","public").eq("featured",true).is("deleted_at",null).order("sort_order").limit(3),
  s.from("services").select("id,title,short_description,icon,featured_image_url,cta_label,cta_url,featured").eq("enabled",true).is("deleted_at",null).order("featured",{ascending:false}).order("sort_order").limit(4),
  s.from("pricing_settings").select("*").eq("singleton_key","default").single(),
  s.from("pricing_packages").select("*").eq("visibility",true).is("deleted_at",null).order("sort_order").limit(3),
  s.from("now_items").select("*").eq("visible",true).order("sort_order"),
  s.from("testimonials").select("id,name,position,company,photo_url,quote,featured,sort_order").eq("visibility",true).is("deleted_at",null).order("featured",{ascending:false}).order("sort_order").limit(6)
 ]);
 const rawWords=h?.rotating_words;
 const words=Array.isArray(rawWords)?rawWords.filter((x:unknown):x is string=>typeof x==="string"):["WORK.","CONNECT.","CONVERT.","SCALE.","MOVE."];
 const groups=["Build","Design","Think","AI"];

 const block:Record<string,ReactNode>={
  hero:<section className="mx-auto grid min-h-[calc(100svh-64px)] w-[min(1440px,calc(100%-32px))] items-center gap-9 py-10 sm:w-[min(1440px,calc(100%-40px))] sm:py-12 lg:grid-cols-[minmax(0,1fr)_360px] lg:gap-12 lg:py-16">
   <div className="hero-intro-copy"><p className="mb-6 text-[11px] font-semibold tracking-[.22em] text-white/35 sm:mb-7">{h?.eyebrow??"OKOH WISDOM / WIKIS TECH"}</p><HeroRotator line1={h?.headline_line_1??"I BUILD WEBSITES &"} line2={h?.headline_line_2??"DIGITAL PRODUCTS THAT"} words={words} enabled={h?.rotation_enabled??true} intervalMs={h?.rotation_interval_ms??2200}/><p className="mt-7 max-w-2xl text-base leading-7 text-white/52 sm:mt-8 sm:text-lg">{h?.supporting_text??"I turn ideas and business problems into useful websites, digital products and intelligent tools — combining software, design, AI and strategy."}</p><div className="mt-7 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><Link href={h?.primary_cta_url??"#work"} className="inline-flex min-h-12 items-center justify-center rounded-full bg-white px-5 py-3 text-sm font-semibold text-[#06070b] transition hover:-translate-y-0.5">{h?.primary_cta_label??"View Selected Work ↓"}</Link><Link href={h?.secondary_cta_url??"/contact"} className="inline-flex min-h-12 items-center justify-center rounded-full border border-white/10 px-5 py-3 text-sm font-medium text-white/75 transition hover:bg-white/[.05]">{h?.secondary_cta_label??"Let's Work Together ↗"}</Link></div></div>
   <aside className="hero-intro-portrait relative mx-auto min-h-[390px] w-full max-w-[420px] sm:min-h-[500px] lg:min-h-[500px] lg:max-w-none"><div className="hero-portrait absolute inset-0 overflow-hidden rounded-[32px] border border-white/10 bg-white/[.025] lg:inset-3 lg:rounded-[38px]">{h?.hero_media_url?<div className="h-full w-full bg-cover bg-center" style={{backgroundImage:`url("${h.hero_media_url}")`}} role="img" aria-label="Portrait of Okoh Wisdom"/>:<><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_35%,rgba(40,103,232,.18),transparent_35%),linear-gradient(180deg,rgba(255,255,255,.04),rgba(255,255,255,.01))]"/><div className="absolute inset-x-6 bottom-6 rounded-2xl border border-white/[.08] bg-black/20 p-4 backdrop-blur"><p className="text-xs font-semibold tracking-[.18em] text-white/35">PORTRAIT / HERO MEDIA</p><p className="mt-2 text-sm text-white/55">Add your portrait from the Home Editor.</p></div></>}</div></aside>
  </section>,

  selected_work:<section id="work" data-reveal="up" className="mx-auto w-[min(1320px,calc(100%-32px))] py-20 sm:w-[min(1320px,calc(100%-40px))] sm:py-24"><p className="text-xs font-semibold tracking-[.18em] text-[#6f8cff]">SELECTED WORK</p><div className="mt-4 flex items-end justify-between gap-4"><h2 className="max-w-4xl text-4xl font-semibold tracking-[-.04em] sm:text-6xl">Built work should look like built work.</h2><Link href="/work" className="hidden text-sm text-white/50 transition hover:text-white sm:block">Explore the full work system ↗</Link></div>{featured?.length?<div className="mt-10 grid gap-6 md:grid-cols-2">{featured.map((p,i)=>{const snap=(p.snapshot??{}) as PublicationSnapshot;const preview=snap.live_url||`/work/${p.slug}`;return <article key={p.project_id} data-reveal="up" data-delay={Math.min(i*90,360)} className={`portfolio-card group overflow-hidden rounded-[28px] border border-white/[.08] bg-[linear-gradient(145deg,rgba(10,24,57,.82),rgba(7,9,16,.96))] ${i===0?"md:col-span-2":""}`}><a href={preview} target={snap.live_url?"_blank":undefined} rel={snap.live_url?"noreferrer":undefined} className="block"><div className={`relative overflow-hidden border-b border-white/[.07] bg-[#081024] ${i===0?"aspect-[16/7]":"aspect-[16/10]"}`}>{snap.card_media_url?<div className="h-full w-full bg-cover bg-center transition duration-700 ease-out group-hover:scale-[1.025]" style={{backgroundImage:`url("${snap.card_media_url}")`}}/>:<div className="absolute inset-0 bg-[radial-gradient(circle_at_28%_28%,rgba(40,103,232,.28),transparent_34%),linear-gradient(145deg,#0b1b40,#070910)]"/>}<span className="absolute right-4 top-4 rounded-full border border-white/10 bg-black/35 px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[.14em] text-white/65 backdrop-blur">{snap.live_url?"Visit live ↗":"View case study ↗"}</span></div></a><div className="p-5 sm:p-6"><p className="text-xs text-[#7d95ff]">0{i+1} · {p.status.replaceAll("_"," ")}</p><Link href={`/work/${p.slug}`} className="mt-3 block"><h3 className="text-3xl font-semibold tracking-[-.04em] transition group-hover:text-[#c0cbff] sm:text-4xl">{p.title}</h3></Link><p className="mt-3 max-w-2xl text-sm leading-6 text-white/45">{snap.problem||p.short_description}</p>{snap.outcome&&<p className="mt-5 text-xs font-medium uppercase tracking-[.14em] text-white/30">Outcome → <span className="text-[#8fa1ff]">{snap.outcome}</span></p>}</div></article>})}</div>:<Empty text="Featured projects will appear here after publishing them from the CMS."/>}<Link href="/work" className="mt-7 inline-block text-sm text-white/60 sm:hidden">Explore all work ↗</Link></section>,

  about_preview:<section data-reveal="up" className="mx-auto grid w-[min(1200px,calc(100%-32px))] gap-8 border-t border-white/[.08] py-20 sm:w-[min(1200px,calc(100%-40px))] sm:py-24 lg:grid-cols-[1fr_300px]"><div><p className="text-xs font-semibold tracking-[.18em] text-[#6f8cff]">ABOUT</p><h2 className="mt-5 max-w-3xl text-4xl font-semibold tracking-[-.04em] sm:text-6xl">{about?.headline}</h2><p className="mt-6 max-w-2xl text-base leading-8 text-white/50">{about?.introduction}</p><Link href="/about" className="mt-7 inline-block text-sm text-white/70">More about me ↗</Link></div><div className="relative hidden min-h-80 lg:block">{about?.portrait_url?<div className="absolute inset-0 rounded-[30px] border border-white/10 bg-cover bg-center" style={{backgroundImage:`url("${about.portrait_url}")`}}/>:<div className="absolute inset-0 rounded-[30px] border border-white/10 bg-white/[.025]"/>}</div></section>,

  capabilities:<section data-reveal="up" className="mx-auto w-[min(1200px,calc(100%-32px))] py-20 sm:w-[min(1200px,calc(100%-40px))] sm:py-24"><p className="text-xs font-semibold tracking-[.18em] text-[#6f8cff]">CAPABILITIES</p><h2 className="mt-4 max-w-3xl text-4xl font-semibold tracking-[-.04em] sm:text-6xl">Different disciplines. One problem-solving process.</h2><div className="mt-10 grid gap-px overflow-hidden rounded-3xl border border-white/[.08] bg-white/[.08] md:grid-cols-2">{groups.map(g=>{const items=(skills??[]).filter(x=>x.group_name===g);return <article key={g} className="bg-[#08090e] p-6 sm:p-8"><p className="text-xs font-semibold tracking-[.16em] text-[#8097ff]">{g.toUpperCase()}</p><p className="mt-8 text-base leading-8 text-white/45">{items.length?items.map(x=>x.name).join(" · "):"Add skills from the CMS."}</p></article>})}</div></section>,

  creative_archive:<section data-reveal="up" className="mx-auto w-[min(1320px,calc(100%-32px))] py-20 sm:w-[min(1320px,calc(100%-40px))] sm:py-24"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-semibold tracking-[.18em] text-[#6f8cff]">VISUAL ARCHIVE</p><h2 className="mt-4 max-w-4xl text-4xl font-semibold tracking-[-.04em] sm:text-6xl">Design work made to communicate, guide and persuade.</h2></div><Link href="/archive" className="hidden text-sm text-white/50 sm:block">View Archive ↗</Link></div>{designs?.length?<div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{designs.map(d=><Link href="/archive" key={d.id} className="group overflow-hidden rounded-2xl border border-white/[.08] bg-white/[.025]"><div className="aspect-[4/5] bg-cover bg-center transition duration-500 group-hover:scale-[1.02]" style={{backgroundImage:`url("${d.image_url}")`}}/><div className="p-4"><p className="text-[10px] uppercase tracking-[.16em] text-white/30">{(d.design_categories as {name?:string}|null)?.name||"Design"}{d.year?` · ${d.year}`:""}</p><h3 className="mt-2 text-lg font-semibold">{d.title}</h3><p className="mt-1 text-sm text-white/35">{d.client}</p></div></Link>)}</div>:<Empty text="Featured design work will appear here from the Design Archive CMS."/>}</section>,

  lab_preview:<section data-reveal="up" className="mx-auto w-[min(1320px,calc(100%-32px))] py-20 sm:w-[min(1320px,calc(100%-40px))] sm:py-24"><div className="grid gap-8 lg:grid-cols-[.65fr_1.35fr]"><div><p className="text-xs font-semibold tracking-[.18em] text-[#6f8cff]">THE LAB</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] sm:text-6xl">Questions worth building answers for.</h2><p className="mt-5 max-w-md text-base leading-7 text-white/45">Games, prototypes, AI experiments and interface studies used to test ideas, learn quickly and discover what is worth taking further.</p><Link href="/lab" className="mt-7 inline-block text-sm text-white/70">Enter the Lab ↗</Link></div><div className="space-y-3">{experiments?.length?experiments.map((x,i)=><Link key={x.id} href={`/lab/${x.slug}`} className="grid gap-4 rounded-2xl border border-white/[.08] bg-white/[.025] p-5 transition hover:bg-white/[.045] sm:grid-cols-[80px_1fr_auto] sm:items-center"><span className="text-2xl text-white/15">0{i+1}</span><div><h3 className="text-lg font-semibold">{x.title}</h3><p className="mt-1 text-sm text-white/35">{x.description}</p></div><span className="text-sm text-white/40">↗</span></Link>):<Empty text="Featured Lab experiments will appear here."/>}</div></div></section>,

  services:<section data-reveal="up" className="mx-auto w-[min(1200px,calc(100%-32px))] py-20 sm:w-[min(1200px,calc(100%-40px))] sm:py-24"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-semibold tracking-[.18em] text-[#6f8cff]">SERVICES</p><h2 className="mt-4 max-w-4xl text-4xl font-semibold tracking-[-.04em] sm:text-6xl">Problems I can help turn into working products.</h2></div><Link href="/services" className="hidden text-sm text-white/50 sm:block">All services ↗</Link></div>{services?.length?<div className="mt-10 divide-y divide-white/[.08] border-y border-white/[.08]">{services.map((x,i)=><Link href={x.cta_url||"/contact"} key={x.id} data-reveal="up" data-delay={Math.min(i*80,320)} className="service-row group grid gap-3 rounded-2xl py-6 md:grid-cols-[80px_1fr_1fr_auto] md:items-center"><span className="text-sm text-white/20">0{i+1}</span><h3 className="text-xl font-semibold">{x.title}</h3><p className="text-sm leading-6 text-white/40">{x.short_description}</p><span className="text-sm text-white/35 transition group-hover:rotate-45">↗</span><div className="service-preview md:col-span-4"><div className="service-preview-inner"><div className="mt-5 grid gap-4 rounded-2xl border border-[#3657ad]/25 bg-[#071126]/75 p-4 md:grid-cols-[1fr_220px] md:items-center"><p className="max-w-2xl text-sm leading-6 text-white/48">{x.short_description}</p>{x.featured_image_url?<div className="aspect-[16/9] overflow-hidden rounded-xl border border-white/[.08] bg-[#081024]"><div className="h-full w-full bg-cover bg-center transition duration-700 group-hover:scale-[1.04]" style={{backgroundImage:`url("${x.featured_image_url}")`}}/></div>:<div className="flex aspect-[16/9] items-center justify-center rounded-xl border border-dashed border-white/10 bg-[#081024] text-[10px] font-semibold uppercase tracking-[.16em] text-white/25">{x.icon||"Service"}</div>}</div></div></div></Link>)}</div>:<Empty text="Enabled services will appear here."/>}</section>,

  pricing:<section data-reveal="up" className="mx-auto w-[min(1200px,calc(100%-32px))] py-20 sm:w-[min(1200px,calc(100%-40px))] sm:py-24">{pricingSettings?.enabled?<><p className="text-xs font-semibold tracking-[.18em] text-[#6f8cff]">PRICING</p><div className="mt-4 flex items-end justify-between gap-4"><h2 className="max-w-3xl text-4xl font-semibold tracking-[-.04em] sm:text-6xl">{pricingSettings.heading}</h2><Link href="/pricing" className="hidden text-sm text-white/50 sm:block">See pricing ↗</Link></div><p className="mt-5 max-w-2xl text-base leading-7 text-white/45">{pricingSettings.description}</p>{packages?.length?<div className="mt-10 grid gap-3 md:grid-cols-3">{packages.map(p=><article key={p.id} className={`rounded-2xl border p-5 ${p.featured?"border-[#5b72ff]/40 bg-[#174fc4]/[.08]":"border-white/[.08] bg-white/[.025]"}`}><p className="text-xs uppercase tracking-[.14em] text-white/30">{p.package_name}</p><p className="mt-8 text-2xl font-semibold">{p.custom_quote?"Custom Quote":p.starting_price!=null?`${p.currency==="NGN"?"₦":p.currency+" "}${Number(p.starting_price).toLocaleString()}`:"Let’s discuss"}</p></article>)}</div>:null}</>:<div className="rounded-3xl border border-white/[.08] bg-white/[.02] p-8"><p className="text-sm text-white/45">Pricing is handled by scope. Tell me what you’re building and we’ll work out a sensible approach.</p><Link href="/contact" className="mt-5 inline-block text-sm text-white/70">Start a conversation ↗</Link></div>}</section>,

  now:<section data-reveal="up" className="mx-auto w-[min(1200px,calc(100%-32px))] py-20 sm:w-[min(1200px,calc(100%-40px))] sm:py-24"><p className="text-xs font-semibold tracking-[.18em] text-[#6f8cff]">RIGHT NOW</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] sm:text-6xl">What has my attention.</h2>{nowItems?.length?<div className="mt-10 grid gap-3 md:grid-cols-2">{nowItems.map(x=><article key={x.id} className="service-card rounded-2xl border border-white/[.08] bg-[#081024]/55 p-5"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-white/30">{x.label}</p>{x.url?<Link href={x.url} className="mt-4 block text-lg text-white/70">{x.text} ↗</Link>:<p className="mt-4 text-lg text-white/70">{x.text}</p>}</article>)}</div>:<Empty text="Add Now items from the CMS to show what you are building, learning and exploring."/>}</section>,

  testimonials:testimonials?.length?<section data-reveal="up" className="mx-auto w-[min(1200px,calc(100%-32px))] py-20 sm:w-[min(1200px,calc(100%-40px))] sm:py-24"><p className="text-xs font-semibold tracking-[.18em] text-[#6f8cff]">TESTIMONIALS</p><h2 className="mt-4 max-w-3xl text-4xl font-semibold tracking-[-.04em] sm:text-6xl">What people say after working together.</h2><div className="mt-10 grid gap-4 md:grid-cols-2">{testimonials.map((x,i)=><article key={x.id} className={`rounded-3xl border border-white/[.08] bg-white/[.025] p-6 sm:p-8 ${i===0&&x.featured?"md:col-span-2":""}`}><p className="text-lg leading-8 text-white/70">“{x.quote}”</p><div className="mt-8"><p className="font-medium">{x.name}</p><p className="mt-1 text-sm text-white/35">{[x.position,x.company].filter(Boolean).join(" · ")}</p></div></article>)}</div></section>:null,

  contact_cta:<section data-reveal="scale" className="mx-auto w-[min(1320px,calc(100%-32px))] py-24 sm:w-[min(1320px,calc(100%-40px))] sm:py-28"><div className="rounded-[30px] border border-white/[.08] bg-[radial-gradient(circle_at_80%_20%,rgba(40,103,232,.14),transparent_35%),rgba(255,255,255,.025)] p-7 sm:rounded-[36px] sm:p-12"><p className="text-xs font-semibold tracking-[.18em] text-[#6f8cff]">HAVE A PROBLEM WORTH SOLVING?</p><h2 className="mt-5 max-w-4xl text-5xl font-semibold tracking-[-.05em] sm:text-7xl">Let’s turn it into something useful.</h2><p className="mt-6 max-w-2xl text-base leading-7 text-white/45">Tell me what is not working, who it affects and what a better outcome should look like. We can work backward from there.</p><Link href="/contact" className="mt-8 inline-flex min-h-12 items-center justify-center rounded-full bg-white px-5 py-3 text-sm font-semibold text-[#06070b]">Start a conversation ↗</Link></div></section>
 };

 return <main className="min-h-screen overflow-hidden bg-[#06070b] text-white"><PublicNav/>{sections?.map(sec=><Fragment key={sec.id}>{block[sec.section_key]??null}</Fragment>)}<PublicFooter/></main>
}

function Empty({text}:{text:string}){return <div className="mt-10 rounded-3xl border border-dashed border-white/10 p-8 text-center text-sm text-white/35 sm:p-10">{text}</div>}
