import {createClient} from "@/lib/supabase/server";
import {createNavigationItem,deleteNavigationItem,saveNavigationItem} from "./actions";
const input="w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm outline-none focus:border-[#5f78ff]/60";
export default async function NavigationPage(){
 const s=await createClient();
 const {data:items}=await s.from("navigation_items").select("*").order("location").order("sort_order");
 return <main className="mx-auto max-w-6xl"><p className="text-xs font-semibold tracking-[.18em] text-[#6f8cff]">SITE / NAVIGATION</p><h1 className="mt-3 text-4xl font-semibold">Navigation</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-white/40">Control header and footer links without editing code. Internal URLs start with /; external URLs must use HTTPS.</p>
 <section className="mt-8 rounded-2xl border border-white/[.08] bg-white/[.02] p-5 sm:p-6"><h2 className="text-lg font-semibold">Add link</h2><form action={createNavigationItem} className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-[1fr_1.4fr_.7fr_.7fr_100px_auto]"><input name="label" required placeholder="Label" className={input}/><input name="href" required placeholder="/work or https://…" className={input}/><select name="location" className={input}><option value="header">Header</option><option value="footer">Footer</option></select><select name="style" className={input}><option value="link">Link</option><option value="cta">CTA</option></select><input name="sortOrder" type="number" defaultValue={0} className={input}/><button className="rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-black">Add</button><div className="flex gap-5 text-sm text-white/50 md:col-span-2 xl:col-span-6"><label><input name="enabled" type="checkbox" defaultChecked className="mr-2"/>Enabled</label><label><input name="isExternal" type="checkbox" className="mr-2"/>External</label></div></form></section>
 <div className="mt-6 space-y-3">{items?.map(x=><form action={saveNavigationItem} key={x.id} className="rounded-2xl border border-white/[.08] bg-white/[.02] p-4"><input type="hidden" name="id" value={x.id}/><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-[1fr_1.4fr_.7fr_.7fr_100px_auto]"><input name="label" defaultValue={x.label} className={input}/><input name="href" defaultValue={x.href} className={input}/><select name="location" defaultValue={x.location} className={input}><option value="header">Header</option><option value="footer">Footer</option></select><select name="style" defaultValue={x.style} className={input}><option value="link">Link</option><option value="cta">CTA</option></select><input name="sortOrder" type="number" defaultValue={x.sort_order} className={input}/><button className="rounded-xl border border-white/10 px-4 py-2.5 text-sm">Save</button></div><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><div className="flex gap-5 text-sm text-white/50"><label><input name="enabled" type="checkbox" defaultChecked={x.enabled} className="mr-2"/>Enabled</label><label><input name="isExternal" type="checkbox" defaultChecked={x.is_external} className="mr-2"/>External</label></div><button formAction={deleteNavigationItem} className="text-xs text-red-300/70">Delete</button></div></form>)}</div></main>
}
